### ISSUE TITLE
deeplab_model res3c and res4c

### ISSUE THREAD

**Issue by qiqi545** [fengguang94/BRINet#3]
Hi, I found that the code in BRINet.py used the attribute res3c and res4c of deeplab_model, but the reference of deeplab have no these two attitudes. Can you give the code of revised deeplab_model ？

**Comment by fengguang94** [comment]
Sorry, my README gave a wrong connection to 'deeplab_model', I fixed it.

**Comment by qiqi545** [comment]
Thanks, but, deeplab_model still does not have these two properties:res3c and res4c. I tried it by including the deeplab101.DeepLabResNetModel which is given by CMSA. And now my fixed version is in training.
